controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
      
    effort_controllers:
      type: effort_controllers/JointGroupEffortController

joint_trajectory_controller:
  ros__parameters:
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
    interface_name: position
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

effort_controllers:
  ros__parameters:
    joints:
      - gripper
      - gripper_sub
    interface_name: effort
    command_interfaces:
      - effort
    state_interfaces:
      - position
      - velocity
      - effort

